A<-bank.full[,]
S<-bank.full[,c(1,6,12)]
View(S)
####EDA
###First moment of Business solution
mean(S$age)
mean(S$balance)
mean(S$duration)
median((S$age))
median(S$balance)
median(S$duration)
mode(S$age)
getmode(S$age)
getmode(S$balance)
getmode(S$duration)
A$job<-as.factor(A$job)
getmode(A$job)
A$marital<-as.factor(A$marital)
getmode(A$marital)
A$education<-as.factor(A$education)
getmode(A$education)
A$default<-as.factor(A$default)
getmode(A$default)
A$housing<-as.factor(A$housing)
getmode(A$housing)
A$loan<-as.factor(A$loan)
getmode(A$loan)
A$contact<-as.factor(A$contact)
getmode(A$contact)
A$day<-as.factor(A$day)
getmode(A$day)
A$month<-as.factor(A$month)
getmode(A$month)
A$campaign<-as.factor(A$campaign)
getmode(A$campaign)
A$pdays<-as.factor(A$pdays)
getmode(A$pdays)
A$previous<-as.factor(A$previous)
getmode(A$previous)
A$poutcome<-as.factor(A$poutcome)
A$y<-as.factor(A$y)
getmode(A$y)
###Second moment of Business solution
var(S$age)
var(S$balance)
var(S$duration)
sd(S$age)
sd(S$balance)
sd(S$duration)
range(S$age)
range(S$balance)
range(S$duration)
rangevalue<-function(x){max(x)-min(x)}
rangevalue(S$age)
rangevalue(S$balance)
rangevalue(S$duration)
###Third moment of Business solution
skewness(S$age)
skewness(S$balance)
skewness(S$duration)
###Fourth moment of Business solution
kurtosis(S$age)
kurtosis(S$balance)
kurtosis(S$duration)
##Visualization Technique
boxplot(S$age)
boxplot(S$balance)
boxplot(S$duration)
barplot(S$age)
barplot(S$balance)
barplot(S$duration)
hist(S$age)
hist(S$balance)
hist(S$duration)
##Normal Quantile Plot(qqplot)
qqnorm(S$age)
qqline(S$age)
qqnorm(S$balance)
qqline(S$balance)
qqnorm(S$duration)
qqline(S$duration)

##Scatter Plot
plot(A$age)
plot(A$job)
plot(A$marital)
plot(A$education)
plot(A$default)
plot(A$balance)
Plot(A$housing)
plot(A$loan)
plot(A$contact)
plot(A$day)
plot(A$month)
plot(A$duration)
plot(A$campaign)
plot(A$pdays)
plot(A$previous)
plot(A$poutcome)
plot(A$y)
###Matrix of Scatter Plot
pairs(A)
###Correlation
cor(S$age,S$balance)
cor(S)

####Model Building
logit<-glm(A$y~.,family="binomial",data=A)
summary(logit)

####Confusion Matrix table
p=predict(logit,type=c("response"),A)
p
View(p)

confusion<-table(p>0.5,A$y)
confusion
View(p)

#####model Accuracy
Accuracy<-sum(diag(confusion)/sum(confusion))
Accuracy
###Receiver Operating Curve(ROC)
rocrpred<-Prediction(p,A$y)
rocrper<-performance(rocrpred,'tpr','fpr')
plot(rocrper,colorize=T)
