c<-Computer_Data[,]
View(c)
new<-Computer_Data[,c(1,2,3,4,5,6)]
View(new)
####EDA
###First moment of Business solution
mean(new$X)
mean(new$price)
mean(new$speed)
mean(new$hd)
mean(new$ram)
mean(new$screen)
median(new$X)
median(new$price)
median(new$speed)
median(new$hd)
median(new$ram)
median(new$screen)
getmode<-function(x){
  uniquv<-unique(x)
  uniquv[which.max(tabulate(match(x,uniquv)))]
}
getmode(new$X)
getmode(new$price)
getmode(new$speed)
getmode(new$hd)
getmode(new$ram)
getmode(new$screen)
###Second moment of Business solution
var(new$X)
var(new$price)
var(new$speed)
var(new$hd)
var(new$ram)
var(new$screen)
sd(new$X)
sd(new$price)
sd(new$speed)
sd(new$hd)
sd(new$ram)
sd(new$screen)
range(new$X)
range(new$price)
range(new$speed)
range(new$hd)
range(new$ram)
range(new$screen)
rangevalue<-function(x){max(x)-min(x)}
rangevalue(new$X)
rangevalue(new$price)
rangevalue(new$speed)
rangevalue(new$hd)
rangevalue(new$ram)
rangevalue(new$screen)
###Third moment of Business solution
skewness(new$X)
skewness(new$price)
skewness(new$speed)
skewness(new$hd)
skewness(new$ram)
skewness(new$screen)
###Fourth moment of Business solution
kurtosis(new$X)
kurtosis(new$price)
kurtosis(new$speed)
kurtosis(new$hd)
kurtosis(new$ram)
kurtosis(new$screen)
##Visualization Technique
boxplot(new$X)
boxplot(new$price)
boxplot(new$speed)
boxplot(new$hd)
boxplot(new$ram)
boxplot(new$screen)
hist(new$X)
hist(new$price)
hist(new$speed)
hist(new$hd)
hist(new$ram)
hist(new$screen)
barplot(new$X)
barplot(new$price)
barplot(new$speed)
barplot(new$hd)
barplot(new$ram)
barplot(new$screen)
###Normal Quantile Plot(qqplot)
qqnorm(new$X)
qqline(new$X)
qqnorm(new$price)
qqline(new$price)
qqnorm(new$speed)
qqline(new$speed)
qqnorm(new$hd)
qqline(new$hd)
qqnorm(new$ram)
qqline(new$ram)
qqnorm(new$screen)
qqline(new$screen)
colnames(new)
summary(new)
pairs(new)
cor(new$speed,new$hd)
cor(new$ram,new$screen)
cor(new)
attach(c)
####Model Building
mod<-lm(price~.,data=c)
summary(mod)

####Diagnostic Plots
###Residual Plot,QQ pLot,Std.Residuals.
plot(mod)####best fit model


#####To get full correlation with y and all x we r using Partial Correlation.
install.packages("corpcor")
library(corpcor)
cor2pcor(cor(new))

