

library(readxl)
read_xlsx("C:/Users/91829/Downloads/EastWestAirlines (4).xlsx",sheet=2)





B<-read_xlsx("C:/Users/91829/Downloads/EastWestAirlines (4).xlsx",sheet=2)[,]
View(B)
####EDA
###First moment of Business solution
mean(B$`ID#`)
mean(B$Balance)
mean(B$Qual_miles)
mean(B$cc1_miles)
mean(B$cc2_miles)
mean(B$cc3_miles)
mean(B$Bonus_miles)
mean(B$Bonus_trans)
mean(B$Flight_miles_12mo)
mean(B$Flight_trans_12)
mean(B$Days_since_enroll)
mean(B$`Award?`)
median(B$`ID#`)
median(B$Balance)
median(B$Qual_miles)
median(B$cc1_miles)
median(B$cc2_miles)
median(B$cc3_miles)
median(B$Bonus_miles)
median(B$Bonus_trans)
median(B$Flight_miles_12mo)
median(B$Flight_trans_12)
median(B$Days_since_enroll)
median(B$`Award?`)
getmode<-function(x){
  uniquv<-unique(x)
  uniquv[which.max(tabulate(match(x,uniquv)))]
}
getmode(B$`ID#`)
getmode(B$Balance)
getmode(B$Qual_miles)
getmode(B$cc1_miles)
getmode(B$cc2_miles)
getmode(B$cc3_miles)
getmode(B$Bonus_miles)
getmode(B$Bonus_trans)
getmode(B$Flight_miles_12mo)
getmode(B$Flight_trans_12)
getmode(B$Days_since_enroll)
getmode(B$`Award?`)
###Second moment of Business solution
var(B$`ID#`)
var(B$Balance)
var(B$Qual_miles)
var(B$cc1_miles)
var(B$cc2_miles)
var(B$cc3_miles)
var(B$Bonus_miles)
var(B$Bonus_trans)
var(B$Flight_miles_12mo)
var(B$Flight_trans_12)
var(B$Days_since_enroll)
var(B$`Award?`)
sd(B$`ID#`)
sd(B$Balance)
sd(B$Qual_miles)
sd(B$cc1_miles)
sd(B$cc2_miles)
sd(B$cc3_miles)
sd(B$Bonus_miles)
sd(B$Bonus_trans)
sd(B$Flight_miles_12mo)
sd(B$Flight_trans_12)
sd(B$Days_since_enroll)
sd(B$`Award?`)
range(B$`ID#`)
range(B$Balance)
range(B$Qual_miles)
range(B$cc1_miles)
range(B$cc2_miles)
range(B$cc3_miles)
range(B$Bonus_miles)
range(B$Bonus_trans)
range(B$Flight_miles_12mo)
range(B$Flight_trans_12)
range(B$Days_since_enroll)
range(B$`Award?`)
rangevalue<-function(x){max(x)-min(x)}
rangevalue(B$`ID#`)
rangevalue(B$Balance)
rangevalue(B$Qual_miles)
rangevalue(B$cc1_miles)
rangevalue(B$cc2_miles)
rangevalue(B$cc3_miles)
rangevalue(B$Bonus_miles)
rangevalue(B$Bonus_trans)
rangevalue(B$Flight_miles_12mo)
rangevalue(B$Flight_trans_12)
rangevalue(B$Days_since_enroll)
rangevalue(B$`Award?`)
###Third moment of Business solution
skewness(B$`ID#`)
skewness(B$Balance)
skewness(B$Qual_miles)
skewness(B$cc1_miles)
skewness(B$cc2_miles)
skewness(B$cc3_miles)
skewness(B$Bonus_miles)
skewness(B$Bonus_trans)
skewness(B$Flight_miles_12mo)
skewness(B$Flight_trans_12)
skewness(B$Days_since_enroll)
skewness(B$`Award?`)
###Fourth moment of Business solution
kurtosis(B$`ID#`)
kurtosis(B$Balance)
kurtosis(B$Qual_miles)
kurtosis(B$cc1_miles)
kurtosis(B$cc2_miles)
kurtosis(B$cc3_miles)
kurtosis(B$Bonus_miles)
kurtosis(B$Bonus_trans)
kurtosis(B$Flight_miles_12mo)
kurtosis(B$Flight_trans_12)
kurtosis(B$Days_since_enroll)
kurtosis(B$`Award?`)
##Visualization Technique
boxplot(B$`ID#`)
boxplot(B$Balance)
boxplot(B$Qual_miles)
boxplot(B$cc1_miles)
boxplot(B$cc2_miles)
boxplot(B$cc3_miles)
boxplot(B$Bonus_miles)
boxplot(B$Bonus_trans)
boxplot(B$Flight_miles_12mo)
boxplot(B$Flight_trans_12)
boxplot(B$Days_since_enroll)
boxplot(B$`Award?`)
hist(B$`ID#`)
hist(B$Balance)
hist(B$Qual_miles)
hist(B$cc1_miles)
hist(B$cc2_miles)
hist(B$cc3_miles)
hist(B$Bonus_miles)
hist(B$Bonus_trans)
hist(B$Flight_miles_12mo)
hist(B$Flight_trans_12)
hist(B$Days_since_enroll)
hist(B$`Award?`)
barplot(B$`ID#`)
barplot(B$Balance)
barplot(B$Qual_miles)
barplot(B$cc1_miles)
barplot(B$cc2_miles)
barplot(B$cc3_miles)
barplot(B$Bonus_miles)
barplot(B$Bonus_trans)
barplot(B$Flight_miles_12mo)
barplot(B$Flight_trans_12)
barplot(B$Days_since_enroll)
barplot(B$`Award?`)
###Normal Quantile Plot(qqplot)
qqnorm(B$`ID#`)
qqline(B$`ID#`)
qqnorm(B$Balance)
qqline(B$Balance)
qqnorm(B$Qual_miles)
qqline(B$Qual_miles)
qqnorm(B$cc1_miles)
qqline(B$cc1_miles)
qqnorm(B$cc2_miles)
qqline(B$cc2_miles)
qqnorm(B$cc3_miles)
qqline(B$cc3_miles)
qqnorm(B$Bonus_miles)
qqline(B$Bonus_miles)
qqnorm(B$Bonus_trans)
qqline(B$Bonus_trans)
qqnorm(B$Flight_miles_12mo)
qqline(B$Flight_miles_12mo)
qqnorm(B$Flight_trans_12)
qqline(B$Flight_trans_12)
qqnorm(B$Days_since_enroll)
qqline(B$Days_since_enroll)
qqnorm(B$`Award?`)
qqline(B$`Award?`)
summary(B)
####Scatter Plot
plot(B$`ID#`)
plot(B$Balance)
plot(B$Qual_miles)
plot(B$cc1_miles)
plot(B$cc2_miles)
plot(B$cc3_miles)
plot(B$Bonus_miles)
plot(B$Bonus_trans)
plot(B$Flight_miles_12mo)
plot(B$Flight_trans_12)
plot(B$Days_since_enroll)
plot(B$`Award?`)
####Matrix of Scatterplot
pairs(B)
####Correlation
cor(B$`ID#`,B$Balance)
cor(B$Qual_miles,B$cc1_miles)
cor(B$cc2_miles,B$cc3_miles)
cor(B$Bonus_miles,B$Bonus_trans)
cor(B$Flight_miles_12mo,B$Flight_trans_12)
cor(B$Days_since_enroll,B$`Award?`)
cor(B)
#####Normalisation using Scale function
nm<-scale(B[,])
summary(nm)#####data should be from -3.4 to +3.4
####Model Building with euclidean.
d<-dist(nm,method="euclidean")
fit<-hclust(d,method="complete")
#####Dendrogram
plot(fit)
#####to get all number in same line using hang=-1.
plot(fit,hang=-1)

####Cut tree when k is 5.
groups<-cutree(fit,k=5)
groups
####to get the tree with rectangle shape with red color when k=4
rect.hclust(fit,k=4,border="red")
#####making matrix assining membership as name in groups
membership<-as.matrix(groups)
######membership in B
fin<-data.frame(B,membership)
View(fin)
###### to make membership in first column
final<-fin[,c(ncol(fin),1:(ncol(fin)-1))]
final
####using aggregate making membership as List with function as mean.
aggregate(B,by=list(fin$membership),FUN = mean)



########K-means Clustering
fit1<-kmeans(nm,4)
str(fit1)
####using Animation to see the clusters
km<-kmeans.ani(nm,8)
str(km)
####to get the  cluster assinging
fit1$cluster
Fl<-data.frame(B,fit1$cluster)
Fl
finl1<-Fl[,c(ncol(Fl),1:(ncol(fin)-1))]
finl1
aggregate(B,by=list(fit1$cluster),FUN = mean)
#####Elbow Curve & Squrt(n/2) to decide the k value

wss<-(nrow(nm)-1)*sum(apply(nm),4,var)
twss()
for(i in 1:12)wss[i]=sum(kmeans(nm,centers =i)$Withiness)
plot(1:8,wss,tybe="b",xlab = "Number of clusters",ylab="within groups sum of Squares")
title(sub="K Means Clustering Scree Plot")

