x<-runif(50)
y<-runif(50)
kavi<-cbind(x,y)
plot(kavi)
km<-kmeans(kavi,4)
windows()
km<-kmeans.ani(kavi,4)
wss<-c()
for(i in 2:15)wss[i]<-sum(kmeans(kavi,centers=i)$withinss)
plot(1:15,wss,type="b",xlab="No of Clusters",ylab="Avg distance")