Z<-`Zoo.(1)`[,]
View(Z)
####EDA
###First moment of Business solution
mean(Z$hair)
mean(Z$feathers)
mean(Z$eggs)
mean(Z$milk)
mean(Z$airborne)
mean(Z$aquatic)
mean(Z$predator)
mean(Z$toothed)
mean(Z$backbone)
mean(Z$breathes)
mean(Z$venomous)
mean(Z$fins)
mean(Z$legs)
mean(Z$tail)
mean(Z$domestic)
mean(Z$catsize)
mean(Z$type)
median(Z$hair)
median(Z$feathers)
median(Z$eggs)
median(Z$milk)
median(Z$airborne)
median(Z$aquatic)
median(Z$predator)
median(Z$toothed)
median(Z$backbone)
median(Z$breathes)
median(Z$venomous)
median(Z$fins)
median(Z$legs)
median(Z$tail)
median(Z$domestic)
median(Z$catsize)
median(Z$type)
getmode<-function(x){
  uniquv<-unique(x)
  uniquv[which.max(tabulate(match(x,uniquv)))]
}
getmode(Z$hair)
getmode(Z$feathers)
getmode(Z$eggs)
getmode(Z$milk)
getmode(Z$airborne)
getmode(Z$aquatic)
getmode(Z$predator)
getmode(Z$toothed)
getmode(Z$backbone)
getmode(Z$breathes)
getmode(Z$venomous)
getmode(Z$fins)
getmode(Z$legs)
getmode(Z$tail)
getmode(Z$domestic)
getmode(Z$catsize)
getmode(Z$type)

###Second moment of Business solution
var(Z$hair)
var(Z$feathers)
var(Z$eggs)
var(Z$milk)
var(Z$airborne)
var(Z$aquatic)
var(Z$predator)
var(Z$toothed)
var(Z$backbone)
var(Z$breathes)
var(Z$venomous)
var(Z$fins)
var(Z$legs)
var(Z$tail)
var(Z$domestic)
var(Z$catsize)
var(Z$type)
sd(Z$hair)
sd(Z$feathers)
sd(Z$eggs)
sd(Z$milk)
sd(Z$airborne)
sd(Z$aquatic)
sd(Z$predator)
sd(Z$toothed)
sd(Z$backbone)
sd(Z$breathes)
sd(Z$venomous)
sd(Z$fins)
sd(Z$legs)
sd(Z$tail)
sd(Z$domestic)
sd(Z$catsize)
sd(Z$type)
range(Z$hair)
range(Z$feathers)
range(Z$eggs)
range(Z$milk)
range(Z$airborne)
range(Z$aquatic)
range(Z$predator)
range(Z$toothed)
range(Z$backbone)
range(Z$breathes)
range(Z$venomous)
range(Z$fins)
range(Z$legs)
range(Z$tail)
range(Z$domestic)
range(Z$catsize)
range(Z$type)
rangevalue<-function(x){max(x)-min(x)}
rangevalue(Z$hair)
rangevalue(Z$feathers)
rangevalue(Z$eggs)
rangevalue(Z$milk)
rangevalue(Z$airborne)
rangevalue(Z$aquatic)
rangevalue(Z$predator)
rangevalue(Z$toothed)
rangevalue(Z$backbone)
rangevalue(Z$breathes)
rangevalue(Z$venomous)
rangevalue(Z$fins)
rangevalue(Z$legs)
rangevalue(Z$tail)
rangevalue(Z$domestic)
rangevalue(Z$catsize)
rangevalue(Z$type)




###Third moment of Business solution
skewness(Z$hair)
skewness(Z$feathers)
skewness(Z$eggs)
skewness(Z$milk)
skewness(Z$airborne)
skewness(Z$aquatic)
skewness(Z$predator)
skewness(Z$toothed)
skewness(Z$backbone)
skewness(Z$breathes)
skewness(Z$venomous)
skewness(Z$fins)
skewness(Z$legs)
skewness(Z$tail)
skewness(Z$domestic)
skewness(Z$catsize)
skewness(Z$type)
###Fourth moment of Business solution
kurtosis(Z$hair)
kurtosis(Z$feathers)
kurtosis(Z$eggs)
kurtosis(Z$milk)
kurtosis(Z$airborne)
kurtosis(Z$aquatic)
kurtosis(Z$predator)
kurtosis(Z$toothed)
kurtosis(Z$backbone)
kurtosis(Z$breathes)
kurtosis(Z$venomous)
kurtosis(Z$fins)
kurtosis(Z$legs)
kurtosis(Z$tail)
kurtosis(Z$domestic)
kurtosis(Z$catsize)
kurtosis(Z$type)
##Visualization Technique
boxplot(Z$hair)
boxplot(Z$feathers)
boxplot(Z$eggs)
boxplot(Z$milk)
boxplot(Z$legs)
boxplot(Z$breathes)
boxplot(Z$catsize)
boxplot(Z$type)
hist(Z$hair)
hist(Z$feathers)
hist(Z$backbone)
hist(Z$fins)
barplot(Z$hair)
barplot(Z$feathers)
barplot(Z$tail)
barplot(Z$type)
###Normal Quantile Plot(qqplot)
qqnorm(Z$hair)
qqline(Z$hair)
qqnorm(Z$feathers)
qqline(Z$feathers)
qqnorm(Z$milk)
qqline(Z$milk)
qqnorm(Z$backbone)
qqline(Z$backbone)
qqnorm(Z$venomous)
qqline(Z$venomous)
qqnorm(Z$fins)
qqline(Z$fins)
qqnorm(Z$tail)
qqline(Z$tail)
qqnorm(Z$domestic)
qqline(Z$domestic)
qqnorm(Z$type)
qqline(Z$type)

###Scatter Plot
plot(Z)
###Matrix of Scatter Plot
pairs(Z)
Z<-Z[,-1]
View(Z)
####Correlation
cor(Z)
#####To see the columns
colnames(Z)
#####Table
table(Z$hair)
table(Z$feathers)
str(Z)
######Replace the 0 with animal and 1 with bird in Z$feathers
Z$feathers<-factor(Z$feathers,levels = c("0","1"),labels = c("A","B"))
str(Z$feathers)
# table or proportation of enteries in the datasets. What % of entry is Animal and % of entry is Birds
round(prop.table(table(Z$feathers))*100,1)######Animals is 80% and Birds is 20%
#####Summarize any 3 numeric features
summary(Z[c("eggs","tail","type")])

#Create a function to normalize the data
norm <- function(x){ 
  return((x-min(x))/(max(x)-min(x)))
}

###TEST
norm(c(1,2,3,4,5))
norm(c(10,20,30,40,50))
#Apply the normalization function to Z dataset
Z_n <- as.data.frame(lapply(Z [2:18], norm))
View(Z_n)
summary(Z_n$milk)
#create training and test datasets
Z_train <- Z_n[1:76,]
Z_test <- Z_n[77:100,]
View(Z_train)
# Build a KNN model on training dataset
library("class")
Z_train_labels<-Z[1:76, 1]
Z_test_labels<-Z[77:100, 1]
Z_test_pred<-knn(train=Z_train,test = Z_test,cl=Z_train_labels,k=23)
View(Z_test_pred)
length(Z_test_pred)
length(Z_test_labels)
###Evaluate Model Prediction
library("gmodels")
####Creating Cross tabulation of predicted Vs Actual
CrossTable(x=Z_test_labels,y=Z_test_pred, prop.chisq = FALSE)
####Different K value
Z_test_pred<-knn(train=Z_train,test = Z_test,cl=Z_train_labels,k=10)
###Evaluate Model Prediction
library("gmodels")
####Creating Cross tabulation of predicted Vs Actual
CrossTable(x=Z_test_labels,y=Z_test_pred, prop.chisq = FALSE)

Z_test_pred<-knn(train=Z_train,test = Z_test,cl=Z_train_labels,k=18)
###Evaluate Model Prediction
library("gmodels")
####Creating Cross tabulation of predicted Vs Actual
CrossTable(x=Z_test_labels,y=Z_test_pred, prop.chisq = FALSE)

