Amlr<-ToyotaCorolla[,]
View(Amlr)
A<-Amlr[,c(3,4,7,9,13,14,16,17,18)]
View(A)
####EDA
###First moment of Business solution
mean(A$Price)
mean(A$Age_08_04)
mean(A$KM)
mean(A$HP)
mean(A$cc)
mean(A$Doors)
mean(A$Gears)
mean(A$Quarterly_Tax)
mean(A$Weight)
median(A$Price)
median(A$Age_08_04)
median(A$KM)
median(A$HP)
median(A$cc)
median(A$Doors)
median(A$Gears)
median(A$Quarterly_Tax)
median(A$Weight)
getmode<-function(x){
  uniquv<-unique(x)
  uniquv[which.max(tabulate(match(x,uniquv)))]
}
getmode(A$Price)
getmode(A$Age_08_04)
getmode(A$KM)
getmode(A$HP)
getmode(A$cc)
getmode(A$Doors)
getmode(A$Gears)
getmode(A$Quarterly_Tax)
getmode(A$Weight)
###Second moment of Business solution
var(A$Price)
var(A$Age_08_04)
var(A$KM)
var(A$HP)
var(A$cc)
var(A$Doors)
var(A$Gears)
var(A$Quarterly_Tax)
var(A$Weight)
sd(A$Price)
sd(A$Age_08_04)
sd(A$KM)
sd(A$HP)
sd(A$cc)
sd(A$Doors)
sd(A$Gears)
sd(A$Quarterly_Tax)
sd(A$Weight)
range(A$Price)
range(A$Age_08_04)
range(A$KM)
range(A$HP)
range(A$cc)
range(A$Doors)
range(A$Gears)
range(A$Quarterly_Tax)
range(A$Weight)
rangevalue<-function(x){max(x)-min(x)}
rangevalue(A$Price)
rangevalue(A$Age_08_04)
rangevalue(A$KM)
rangevalue(A$HP)
rangevalue(A$cc)

###Third moment of Business solution
skewness(A$Price)
skewness(A$Age_08_04)
skewness(A$KM)
skewness(A$HP)
skewness(A$cc)
skewness(A$Doors)
skewness(A$Gears)
skewness(A$Quarterly_Tax)
skewness(A$Weight)

###Fourth moment of Business solution
kurtosis(A$Price)
kurtosis(A$Age_08_04)
kurtosis(A$KM)
kurtosis(A$HP)
kurtosis(A$cc)
kurtosis(A$Doors)
kurtosis(A$Gears)
kurtosis(A$Quarterly_Tax)
kurtosis(A$Weight)


##Visualization Technique
boxplot(A$Price)
boxplot(A$Age_08_04)
boxplot(A$KM)
boxplot(A$HP)
boxplot(A$cc)
boxplot(A$Doors)
boxplot(A$Gears)
boxplot(A$Quarterly_Tax)
boxplot(A$Weight)
hist(A$Price)
hist(A$Age_08_04)
hist(A$KM)
hist(A$HP)
hist(A$cc)
hist(A$Doors)
hist(A$Gears)
hist(A$Quarterly_Tax)
hist(A$Weight)
barplot(A$Price)
barplot(A$Age_08_04)
barplot(A$KM)
barplot(A$HP)
barplot(A$cc)
barplot(A$Doors)
barplot(A$Gears)
barplot(A$Quarterly_Tax)
barplot(A$Weight)
###Normal Quantile Plot(qqplot)
qqnorm(A$Price)
qqline(A$Price)
qqnorm(A$Age_08_04)
qqline(A$Age_08_04)
qqnorm(A$KM)
qqline(A$KM)
qqnorm(A$HP)
qqline(A$HP)
qqnorm(A$cc)
qqline(A$cc)
qqnorm(A$Doors)
qqline(A$Doors)
qqnorm(A$Gears)
qqline(A$Gears)
qqnorm(A$Quarterly_Tax)
qqline(A$Quarterly_Tax)
qqnorm(A$Weight)
qqline(A$Weight)



###Scatter Plot
plot(A$Price,A$Age_08_04)
plot(A$KM,A$HP)
plot(A$cc,A$Doors)
plot(A$Quarterly_Tax,A$Gears)
plot(A$Weight,A$Price)

###Matrix of Scatter Plot
pairs(A)
####Correlation
cor(A$Price,A$Age_08_04)
cor(A$Price,A$KM)
cor(A$Price,A$HP)
cor(A$Price,A$cc)
cor(A$Price,A$Doors)
cor(A$Price,A$Gears)
cor(A$Price,A$Quarterly_Tax)
cor(A$Price,A$Weight)
cor(A)
#######MOdel Building
ml<-lm(A$Price~.,data=A)
summary(ml)
####Diagnostic Plots
###Residual Plot,QQ pLot,Std.Residuals.
plot(ml)####best fit model

#####To get full correlation with y and all x we r using Partial Correlation.
install.packages("corpcor")
library(corpcor)
cor2pcor(cor(A))



 
